export const types = {
	CHANGE_INPUT: 'CHANGE_INPUT',
	GET_LOGIN_ASYNC: 'GET_LOGIN_ASYNC',
	POST_LOGIN_ASYNC: 'POST_LOGIN_ASYNC',
	IS_TOKEN: 'IS_TOKEN',
	ERROR_LOGIN_ASYNC: 'ERROR_LOGIN_ASYNC',
	IS_LOGOUT: 'IS_LOGOUT',
};