export const types = {
	//Toys
	GET_TOYS_TRANSACTIONS_ASYNC: 'GET_TOYS_TRANSACTIONS_ASYNC',
	GET_TOYS_ASYNC: 'GET_TOYS_ASYNC',
	POST_TOYS_ASYNC: 'POST_TOYS_ASYNC',
	DELETE_TOY_ASYNC: 'DELETE_TOY_ASYNC',
	UPDATE_TOY_ASYNC: 'UPDATE_TOY_ASYNC',
	PUT_TOYS: 'PUT_TOYS',
	PUT_TOY: 'PUT_TOY',
	DELETE_TOY: 'DELETE_TOY',
	UPDATE_TOY: 'UPDATE_TOY',
	//Categories
	GET_CATEGORIES_ASYNC: 'GET_CATEGORIES_ASYNC',
	POST_CATEGORY_ASYNC: 'POST_CATEGORY_ASYNC',
	DELETE_CATEGORY_ASYNC: 'DELETE_CATEGORY_ASYNC',
	UPDATE_CATEGORY_ASYNC: 'UPDATE_CATEGORY_ASYNC',

	ADD_CATEGORY: 'ADD_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',
	PUT_CATEGORIES: 'PUT_CATEGORIES',
	UPDATE_CATEGORY: 'UPDATE_CATEGORY',
	GET_CATEGORIES_AND_TOYS: 'GET_CATEGORIES_AND_TOYS',
	//Transactions
	GET_TRANSACTIONS_ASYNC: 'GET_TRANSACTIONS_ASYNC',
	GET_TRANSACTIONS_ID_ASYNC: 'GET_TRANSACTIONS_ID_ASYNC',
	POST_TRANSACTIONS_ASYNC: 'POST_TRANSACTIONS_ASYNC',
	PUT_TRANSACTIONS: 'PUT_TRANSACTIONS',
	PUT_TRANSACTIONS_ID: 'PUT_TRANSACTIONS_ID'
};